import { useState, useEffect } from "react";

const BACKEND = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8080";

export default function Home() {
  const [repoUrl, setRepoUrl] = useState("");
  const [workflowId, setWorkflowId] = useState(null);
  const [status, setStatus] = useState("idle"); // idle | running | done | error
  const [plan, setPlan] = useState(null);
  const [error, setError] = useState(null);
  const [polling, setPolling] = useState(false);

  useEffect(() => {
    let timer;
    if (workflowId && polling) {
      const poll = async () => {
        try {
          const res = await fetch(`${BACKEND}/api/scan/${workflowId}`);
          if (res.status === 200) {
            const data = await res.json();
            if (data.status === "done") {
              setPlan(data.plan);
              setStatus("done");
              setPolling(false);
            } else if (data.status === "running") {
              setStatus("running");
            } else {
              // unknown state
              setStatus("running");
            }
          } else if (res.status === 404) {
            // not found yet
            setStatus("running");
          } else {
            const txt = await res.text();
            setError(`Unexpected response: ${res.status} ${txt}`);
            setStatus("error");
            setPolling(false);
          }
        } catch (err) {
          setError(String(err));
          setStatus("error");
          setPolling(false);
        }
      };

      // initial immediate poll
      poll();
      // then poll every 2500ms
      timer = setInterval(poll, 2500);
    }
    return () => clearInterval(timer);
  }, [workflowId, polling]);

  const startScan = async () => {
    setError(null);
    setPlan(null);
    setWorkflowId(null);

    if (!repoUrl || !repoUrl.startsWith("http")) {
      setError("Please enter a valid repo URL (e.g. https://github.com/owner/repo.git)");
      return;
    }

    setStatus("running");
    try {
      const res = await fetch(`${BACKEND}/api/scan`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repo_url: repoUrl }),
      });

      if (res.status === 202 || res.ok) {
        const data = await res.json();
        setWorkflowId(data.workflow_id || data.workflowId || data.id);
        setPolling(true);
        setStatus("running");
      } else {
        const txt = await res.text();
        setError(`Scan request failed: ${res.status} ${txt}`);
        setStatus("error");
      }
    } catch (err) {
      setError(String(err));
      setStatus("error");
    }
  };

  const copyIssueTemplate = () => {
    if (!plan) return;
    const ownerRepo = plan.repo_url || repoUrl;
    const title = `[AutoSec AI] Security findings & suggested fix for ${ownerRepo}`;
    let body = `AutoSec AI scanned ${ownerRepo} and suggests the following remediation:\n\n**Summary:**\n${plan.summary}\n\n**Suggested fix strategy:** ${plan.fix_strategy}\n\n`;
    if ( plan.from_image && plan.to_image) {
      body += `Suggested change (example patch):\n\n\`\`\`diff\n-FROM ${plan.from_image}\n+FROM ${plan.to_image}\n\`\`\`\n\n`;
    }
    body += "\n_This issue content was generated by AutoSec AI._\n";
    navigator.clipboard.writeText(`# ${title}\n\n${body}`).then(
      () => alert("Issue template copied to clipboard"),
      (err) => alert("Failed to copy: " + err)
    );
  };

  return (
    <div style={styles.page}>
      <h1 style={styles.h1}>AutoSec AI — Scan & Fix Preview</h1>

      <div style={styles.card}>
        <label style={styles.label}>Repository URL (Note: This currently supports public GitHub repositories that use the main branch and include dependencies.)</label>
        <input
          style={styles.input}
          placeholder="https://github.com/owner/repo.git"
          value={repoUrl}
          onChange={(e) => setRepoUrl(e.target.value)}
        />
        <div style={styles.row}>
          <button style={styles.button} onClick={startScan}>
            Start Scan
          </button>
          <button
            style={{ ...styles.button, marginLeft: 8 }}
            onClick={() => {
              setRepoUrl("");
              setWorkflowId(null);
              setPlan(null);
              setStatus("idle");
            }}
          >
            Reset
          </button>
        </div>

        {status === "running" && (
          <div style={{ marginTop: 12 }}>
            <strong>Scan in progress</strong>
            {workflowId && <div>Workflow ID: <code>{workflowId}</code></div>}
            <div style={{ marginTop: 8 }}>Polling for results...</div>
          </div>
        )}

        {status === "done" && plan && (
          <div style={{ marginTop: 16 }}>
            <h3>AutoFix Plan</h3>
            <div><strong>Summary</strong></div>
            <p>{plan.summary}</p>

            <div><strong>Strategy</strong></div>
            <p style={styles.badge}>{plan.fix_strategy}</p>

            {plan.from_image && plan.to_image&& (
              <div>
                <div><strong>From</strong></div>
                <pre style={styles.code}>{plan.from_image}</pre>
                <div><strong>To</strong></div>
                <pre style={styles.code}>{plan.to_image}</pre>
              </div>
            )}

            <div style={{ marginTop: 12 }}>
              <button style={styles.button} onClick={copyIssueTemplate}>
                Copy Issue Template
              </button>
            </div>
          </div>
        )}

        {status === "error" && (
          <div style={{ marginTop: 12, color: "crimson" }}>
            <strong>Error:</strong> {error}
          </div>
        )}
      </div>

      <footer style={{ marginTop: 24, color: "#666" }}>
        Backend: <code>{BACKEND}</code> — Remember to allow CORS from your Vercel domain.
      </footer>
    </div>
  );
}

const styles = {
  page: {
    maxWidth: 880,
    margin: "36px auto",
    padding: 16,
    fontFamily: "Inter,system-ui,Arial,sans-serif",
  },
  h1: { marginBottom: 8 },
  card: {
    border: "1px solid #eee",
    padding: 18,
    borderRadius: 8,
    boxShadow: "0 4px 12px rgba(0,0,0,0.03)",
  },
  label: { display: "block", marginBottom: 8, fontWeight: 600 },
  input: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid #ddd",
    marginBottom: 10,
  },
  row: { display: "flex", alignItems: "center" },
  button: {
    background: "#111",
    color: "white",
    padding: "8px 12px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
  },
  badge: {
    display: "inline-block",
    padding: "6px 10px",
    background: "#f0f3ff",
    borderRadius: 999,
    color: "#1f3fff",
    fontWeight: 600,
  },
  code: {
    background: "#0f1724",
    color: "#dbeafe",
    padding: 10,
    borderRadius: 6,
    overflowX: "auto",
  },
};
